repos:
-   repo: https://github.com/python/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.6.0
    hooks:
    -   id: zimports

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-import-single==0.1.5
          - flake8-builtins
          - pydocstyle
          - pygments

